### Импортируем библиотеки

In [24]:
import pandas as pd
import numpy as np
import re

### Загрузка данных

In [25]:
pd.set_option('display.max_columns', None)                          # устанавливаем отображение всех столбцов
df = pd.read_csv('../data/_data.csv', index_col='Unnamed: 0')       # Загружаем файл
df.head(5)                                                          # Выводим первые 5 строк для проверки

,ID объявления,Количество комнат,Тип,Метро,Адрес,"Площадь, м2",Дом,Парковка,Цена,Телефоны,Описание,Ремонт,"Площадь комнат, м2",Балкон,Окна,Санузел,Можно с детьми/животными,Дополнительно,Название ЖК,Серия дома,"Высота потолков, м",Лифт,Мусоропровод,Ссылка на объявление
0,271271157,4,Квартира,м. Смоленская (9 мин пешком),"Москва, улица Новый Арбат, 27",200.0/20.0,"5/16, Монолитный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79166369231,Без комиссии для нанимателя! Бонус коллегам 12...,Дизайнерский,NaN,NaN,NaN,NaN,"Можно с детьми, Можно с животными","Мебель в комнатах, Мебель на кухне, Ванна, Душ...","Новый Арбат, 2010",NaN,3.0,"Пасс (4), Груз (1)",Да,https://www.cian.ru/rent/flat/271271157
1,271634126,4,Квартира,м. Смоленская (8 мин пешком),"Москва, улица Новый Арбат, 27",198.0/95.0/18.0,"5/16, Монолитно-кирпичный",подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...",+79850608590,Лот 93107. Елена Анисимова.\n\nБонус агенту 50...,Дизайнерский,25 25 20 25,NaN,На улицу и двор,"Совмещенный (2), Раздельный (1)",Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.5,"Пасс (1), Груз (1)",Нет,https://www.cian.ru/rent/flat/271634126
2,271173086,"4, Оба варианта",Квартира,м. Смоленская (7 мин пешком),"Москва, улица Новый Арбат, 27",200.0/116.0/4.0,5/16,подземная,"500000.0 руб./ За месяц, Залог - 500000 руб., ...","+79672086536, +79099269384","ID 36380: Шикарная 4-х км. квартира в ЖК ""Нов...",Евроремонт,NaN,NaN,На улицу и двор,Совмещенный (3),Можно с детьми,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",Новый Арбат,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/271173086
3,272197456,"4, Оба варианта",Квартира,м. Смоленская (3 мин пешком),"Москва, переулок Плотников, 21С1",170.0/95.0/17.0,5/6,подземная,"400000.0 руб./ За месяц, Залог - 400000 руб., ...","+79660342340, +79099269384",ID 31618: Эксклюзивное предложение. Современн...,Евроремонт,14-42-20-19,NaN,На улицу и двор,Совмещенный (3),Можно с животными,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",NaN,NaN,3.2,Пасс (1),NaN,https://www.cian.ru/rent/flat/272197456
4,273614615,2,Квартира,м. Арбатская (7 мин пешком),"Москва, улица Новый Арбат, 15",58.0/38.0/5.0,"12/26, Панельный",NaN,"225000.0 руб./ За месяц, Залог - 225000 руб., ...",+79852432860,Лот 111542. Татьяна Лучкина.\n\nБонус агенту 5...,Евроремонт,20 18,NaN,На улицу и двор,Совмещенный (2),NaN,"Мебель в комнатах, Мебель на кухне, Ванна, Душ...",The Book,NaN,3.9,"Пасс (1), Груз (1)",Да,https://www.cian.ru/rent/flat/273614615

### Выводим список столбцов с количеством уникальных значений

In [26]:
feature_names = df.columns.tolist() 
for column in feature_names: 
    print(column, '=' ,df[column].nunique())

ID  объявления = 23368
Количество комнат = 24
Тип = 1
Метро = 5866
Адрес = 12850
Площадь, м2 = 11255
Дом = 2565
Парковка = 5
Цена = 3922
Телефоны = 13172
Описание = 23078
Ремонт = 4
Площадь комнат, м2 = 3990
Балкон = 18
Окна = 3
Санузел = 20
Можно с детьми/животными = 3
Дополнительно = 528
Название ЖК = 1798
Серия дома = 393
Высота потолков, м = 95
Лифт = 34
Мусоропровод = 2
Ссылка на объявление = 23368

### Удаляем столбцы, не имеющие смысловой нагрузки для модели

In [27]:
df.drop(['Тип', 'Телефоны', 'Дополнительно' , 'Название ЖК', 'Серия дома', 'Ссылка на объявление'], axis = 1, inplace=True)
# столбец "Тип" нам не подходит, ввиду отсутствия в нем вариантов (1 уникальное значение)
# остальные столбцы, на наш взгляд, содержат информацию, не влияющую на работу модели машинного обучения

### Обрабатываем колонку "Количество комнат"

In [28]:
def extract_digits(text):                                                                                   # вспомогательная функция, вытягивающая из строки числа
    digits = re.findall(r'\d+', str(text))
    if len(digits) == 1:
        return int(digits[0])
    return sum(map(int, digits))


df['Количество комнат'] = df['Количество комнат'].apply(extract_digits)                                     # перезаполняем колонку "Количество комнат"
df['Количество комнат'] = df['Количество комнат'].fillna(df['Площадь комнат, м2'].apply(extract_digits))    # заполняем пустые значения, суммируя площадь комнат (если указано)
df.drop(['Площадь комнат, м2'], axis=1, inplace=True)                                                       # удаляем ненужный больше столбец "Площадь комнат"

### Обрабатываем колонку "Метро"

In [29]:
def time_from_metro(text):                                          # вспомогательная функция, вытягивающая из строки число, идущее перед строкой "мин пешком"
    match = re.search(r'\((\d+)\s*мин\s*пешком\)', str(text))
    if match:
        return int(match.group(1))
    else:
        return None

df['Метро'] = df['Метро'].apply(time_from_metro)                    # перезаполняем колонку "Метро"
df['Метро'] = df['Метро'].fillna(0)                                 # заполняем пустые значения 0, считаем, что 0 - расстояние до метро не известно
# К сожалению, мы не знаем, как модель обрабатывает входные данные, поэтому здесь мы сделали на основе наших предположений
# мы считали, что высчитывать расстояние до метро у пропущенных значений не совсем корректно, ввиду того, что это должно быть какое-то константное значение, 
# а не рассчитанное. В то же время, оно никак не связано с другими характеристиками, поэтому внесенное нами значение (рассчитанное по любой из формул) может
# привести к искажению результата работы модели
# В то же время, мы предположили, что модель может быть настроена таким образом, что любая цифра, отличная от 0, может считаться указанным расстоянием до метро,
# в то время, как 0 означает, что значение не указано. Основываясь на этом предположении мы и реализовали данную графу.

### Обрабатываем колонку "Адрес"

In [30]:
df = df[df['Адрес'].str.contains("Москва")].reset_index(drop = True)    # исключаем из датасета записи, в которых адрес не равен значению Москва
df.drop('Адрес', axis=1, inplace=True)                                  # удаляем колонку "Адрес" за ненадобностью

### Обрабатываем колонку "Площадь, м2"

In [31]:
def extract_first_digit(text):                                          # вспомогательная функция, вытягивающая из строки первое число
    values = re.search(r'\d+', str(text))
    return int(values.group())
df['Площадь, м2'] = df['Площадь, м2'].apply(extract_first_digit)        # перезаполняем колонку "Площадь, м2"

### Обрабатываем колонку "Дом", создаем 2 новых колонки "Этаж" и "Высота дома"

In [32]:
df['Этаж']=df['Дом'].str.split(',').str[0].str.split('/').str[0]                        # создаем колонку "Этаж" на основе данных в графе "Дом"
df['Высота дома']=df['Дом'].str.split(',').str[0].str.split('/').str[1]                 # создаем колонку "Высота дома" на основе данных в графе "Дом"

df.drop(['Дом'], axis=1, inplace=True)                                                  # удаляем колонку "Дом" за ненадобностью

### Обрабатываем колонку "Парковка"

In [33]:
df['Парковка'] = df['Парковка'].fillna('0').replace({'подземная': '1', 'наземная': '2', 'открытая': '3', 'многоуровневая': '4', 'на крыше': '5'})
# меняем данные в графе "Парковка", основываясь на следующие характеристики:
# 0 - парковка отсутствует
# 1 - подземная парковка
# 2 - наземная парковка
# 3 - открытая парковка
# 4 - многоуровневая парковка
# 5 - парковка на крыше

### Обрабатываем колонку "Цена", создаем колонку "Коммунальные услуги включены"

In [34]:
def public_utilities(text):                                                 # вспомогательная функция, находящая вхождение подстроки "Коммунальные услуги включены" в строку
    match = re.search('Коммунальные услуги включены', str(text))
    return 1 if match else 0

df['Коммунальные услуги включены'] = df['Цена'].apply(public_utilities)     # перезаполняем колонку "Коммунальные услуги включены"
df['Цена']=df['Цена'].apply(extract_first_digit)                            # перезаполняем колонку "Цена"

### Создаем колонку "Цена за квадратный метр", чтобы с её помощью заполнить пустые поля в поле количество комнат

In [35]:
df['Цена за квадратный метр'] = df['Цена'] / df['Площадь, м2']                              # создаем новую колонку 'Цена за квадратный метр'
df['Цена за квадратный метр'] = df['Цена за квадратный метр'].round(2)                      # округляем значения в этой колонке до 2-х знаков после запятой

res = df.groupby(['Количество комнат'])['Цена за квадратный метр'].median()                 # находим среднее значение цены за квадратный метр с группировкой по 
del res[0]                                                                                  # количеству комнат
def quanttity_room(square_price):                                                           # # вспомогательная функция, определяющая количество комнат в зависимости
    for i in range(1, len(res)):                                                            # от стоимости квадратного метра
        if res[i] <= square_price <= res[i + 1]:
            return i if (square_price - res[i]) < (res[i + 1] - square_price) else i + 1
        elif square_price < res[1]:
            return 1
        elif square_price > res[len(res)]:
            return len(res)

df['Количество комнат'] = df.apply(lambda row: quanttity_room(row['Цена за квадратный метр']) if row['Количество комнат'] == 0 else row['Количество комнат'], axis=1)
# Заполняем количество комнат в позициях, где у нас был 0
# Можно было считать количество комнат в зависимости от площади квартиры, или даже в зависимости от площади и цены за квадратный метр,
# но к сожалению, у нас было ограничение по времени, и опять же, мы можем только предполагать, как работает модель. 
# В итоге решили остановиться на этом варианте

### Обрабатываем колонку "Ремонт"

In [36]:
def extract_renovation(description):                                                    # вспомогательная функция, находящая вхождение подстрок из списка в исходную строку
    patterns = ['Дизайнерский', 'Евроремонт', 'Косметический', 'Без ремонта']
    
    for remont_type in patterns:
        if re.search(remont_type, str(description), re.IGNORECASE):
            return remont_type
    return 'Не указан'

df['Ремонт'] = df.apply(lambda row: extract_renovation(row['Описание']) if pd.isna(row['Ремонт']) else row['Ремонт'], axis=1)
# перезаполняем колонку "Ремонт", заполняем ее данными из колонки "Описание" (при наличии), если данные в колонке "Ремонт" отсутствуют

df['Ремонт'] = df['Ремонт'].replace({'Не указан':'0', 'Без ремонта':'1', 'Косметический':'2', 'Евроремонт':'3', 'Дизайнерский':'4'})
# заменяем данные в колонке "Ремонт" на числовой признак согласно следующему шаблону:
# 0 - Не указан
# 1 - Без ремонта
# 2 - Косметический ремонт
# 3 - Евроремонт
# 4 - :'3', 'Дизайнерский ремонт

df.drop(['Описание'], axis=1, inplace=True)         # удаляем колонку "Описание" за ненадобностью

### Обрабатываем колонку "Балкон"

In [37]:
def extract_balcony(text):                                                      # вспомогательная функция, находящая вхождение указанных подстрок в исходную строку
    if re.search('Балкон', str(text)) and re.search('Лоджия', str(text)):
        return 3
    elif re.search('Лоджия', str(text)):
        return 2
    elif re.search('Балкон', str(text)):
        return 1
    else:
        return 0
    
df['Балкон']=df['Балкон'].fillna(0).apply(extract_balcony)                      
# заменяем данные в колонке "Балкон" на числовой признак согласно следующему шаблону:
# 0 - не указано
# 1 - есть только балкон
# 2 - есть только лоджия
# 3 - есть балкон и лоджия

### Обрабатываем колонку "Окна"

In [38]:
df['Окна'] = df['Окна'].fillna('0').replace({'На улицу':'1', 'Во двор':'2', 'На улицу и двор':'3'})
# заменяем данные в колонке "Окна" на числовой признак согласно следующему шаблону:
# 0 - не указано
# 1 - на улицу
# 2 - во двор
# 3 - на улицу и двор

### Обрабатываем колонку "Санузел"

In [39]:
def extract_bathroom(text):                                                             # вспомогательная функция, находящая вхождение указанных подстрок в исходную строку
    if re.search('Раздельный', str(text)) and re.search('Совмещенный', str(text)):
        return 3
    elif re.search('Раздельный', str(text)):
        return 2
    elif re.search('Совмещенный', str(text)):
        return 1
    else:
        return 0
    
df['Санузел']=df['Санузел'].fillna(0).apply(extract_bathroom)
# заменяем данные в колонке "Санузел" на числовой признак согласно следующему шаблону:
# 0 - не указано
# 1 - совмещенный санузел
# 2 - раздельный санзел
# 3 - совмещенный и раздельный санузел

### Обрабатываем колонку "Можно с детьми/животными"

In [40]:
def replace_children_pets(text):                                                                # вспомогательная функция, находящая вхождение указанных подстрок в исходную строку
    patterns = ['Можно с детьми, Можно с животными', 'Можно с детьми', 'Можно с животными']
    for allow in patterns:
        if re.search(allow, str(text)):
            return allow
    return 'Не указан'

df['Можно с детьми/животными'] = df['Можно с детьми/животными'].fillna('0').replace({'Можно с детьми':'1', 'Можно с животными':'2', 'Можно с детьми, Можно с животными':'3'})
# заменяем данные в колонке "Можно с детьми/животными" на числовой признак согласно следующему шаблону:
# 0 - не указано
# 1 - можно с детьмиМетро
# 2 - можно с животными
# 3 - можно с детьми и животными

### Обрабатываем колонку "Высота потолков, м"

In [41]:
median_value = df['Высота потолков, м'].median()                            # считаем среднее значение по колонке
df['Высота потолков, м'] = df['Высота потолков, м'].fillna(median_value)    # заполняем пропуски средним значением (посчитали нецелесообразным применение более сложных формул)

### Обрабатываем колонку "Лифт"

In [42]:
def extract_elevator(text):                                                     # вспомогательная функция, находящая вхождение указанных подстрок в исходную строку
    if re.search('Пасс', str(text)) and re.search('Груз', str(text)):
        return 3
    elif re.search('Груз', str(text)):
        return 2
    elif re.search('Пасс', str(text)):
        return 1
    else:
        return 0
    
df['Лифт']=df['Лифт'].fillna(0).apply(extract_elevator)
# заменяем данные в колонке "Лифт" на числовой признак согласно следующему шаблону:
# 0 - не указано
# 1 - пассажирский
# 2 - грузовой
# 3 - пассажирский и грузовой

### Обрабатываем колонку "Мусоропровод"

In [43]:
df['Мусоропровод'] = df['Мусоропровод'].fillna('0').replace({'Нет': '1', 'Да': '2'})
# меняем содержимое в графе "Мусоропровод" на числовой признак: 0 - не указано, 1 - мусоропровода нет, 2 - мусоропровод есть

### Переносим колонку "Цена" в конец датасета

In [44]:
price_col = df['Цена']                                  # сохраняем исходную колонку "Цена"
df.drop(['Цена'], axis=1, inplace=True)                 # удаляем её из датафрейма
df.insert(len(df.columns), 'Цена', price_col)           # вставляем сохранённую колонку "Цена" в конец датафрейма

### Меняем все наименования столбцов на английский язык

In [45]:
df.rename(columns={'ID  объявления':'ID_announcement', 'Количество комнат':'rooms', 'Метро':'metro', 'Площадь, м2':'square_flat', 
                   'Парковка':'parking_lot', 'Цена':'price', 'Ремонт':'renovation', 'Балкон':'balcony', 'Окна':'windows', 
                   'Санузел':'bathroom', 'Можно с детьми/животными':'kids_animals', 'Высота потолков, м':'ceiling_height', 
                   'Лифт':'elevator', 'Мусоропровод':'garbage_chute', 'Этаж' :'floor', 'Высота дома':'house_height', 
                   'Цена за квадратный метр':'square_price', 'Коммунальные услуги включены':'public_utilities'}, inplace=True)

### Проверяем типы ячеек в датасете

In [46]:
df.dtypes

ID_announcement       int64
rooms                 int64
metro               float64
square_flat           int64
parking_lot          object
renovation           object
balcony               int64
windows              object
bathroom              int64
kids_animals         object
ceiling_height      float64
elevator              int64
garbage_chute        object
floor                object
house_height         object
public_utilities      int64
square_price        float64
price                 int64
dtype: object

### Приводим все типы ячеек к числовым значениям

In [47]:
df['metro'] = df['metro'].astype(int)
df['parking_lot'] = df['parking_lot'].astype(int)
df['renovation'] = df['renovation'].astype(int)
df['windows'] = df['windows'].astype(int)
df['kids_animals'] = df['kids_animals'].astype(int)
df['garbage_chute'] = df['garbage_chute'].astype(int)
df['floor'] = df['floor'].astype(int)
df['house_height'] = df['house_height'].astype(int)

### Повторно проверяем типы ячеек в датасете

In [48]:
df.dtypes

ID_announcement       int64
rooms                 int64
metro                 int64
square_flat           int64
parking_lot           int64
renovation            int64
balcony               int64
windows               int64
bathroom              int64
kids_animals          int64
ceiling_height      float64
elevator              int64
garbage_chute         int64
floor                 int64
house_height          int64
public_utilities      int64
square_price        float64
price                 int64
dtype: object

### Выгружаем итоговый датасет в файл .csv

In [51]:
df.to_csv('../realises/data_dragons_data.csv')